# Generated by Django 4.2.23 on 2025-08-10 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reset', models.DateField(default=django.utils.timezone.now)),
                ('water_intake', models.IntegerField(default=1)),
                ('sleep_hours', models.FloatField(default=1)),
                ('water_goal', models.IntegerField(default=8)),
                ('sleep_goal', models.FloatField(default=8.0)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
