# Generated by Django 4.2.23 on 2025-08-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='water_goal',
            field=models.FloatField(default=8.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='water_intake',
            field=models.FloatField(default=0),
        ),
    ]
