# Generated by Django 4.2.23 on 2025-08-12 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_sleep_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_goal',
            field=models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='water_goal',
            field=models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='water_intake',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
