# Generated by Django 4.2.23 on 2025-08-15 09:59

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_sleep_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=profiles.models.avatar_upload_path),
        ),
    ]
