# Generated by Django 4.2.23 on 2025-08-15 10:15

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to=profiles.models.avatar_upload_path),
        ),
    ]
