# Generated by Django 4.2.23 on 2025-08-16 13:20

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dpd5sqeqc/image/upload/v1755350288/avatar_rma9mg.png', null=True, upload_to=profiles.models.avatar_upload_path),
        ),
    ]
