# Generated by Django 4.2.23 on 2025-08-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sleep_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='water_intake',
            field=models.IntegerField(default=0),
        ),
    ]
