# Generated by Django 4.2.23 on 2025-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile_sleep_hours_userprofile_water_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sleep_goal',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='water_goal',
            field=models.IntegerField(default=8),
        ),
    ]
