# Generated by Django 4.2.23 on 2025-08-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userprofile_sleep_goal_userprofile_water_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_hours',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='water_intake',
            field=models.IntegerField(default=1),
        ),
    ]
