# Generated by Django 4.2.23 on 2025-08-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_userprofile_description_alter_task_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
