# Generated by Django 4.2.23 on 2025-08-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
